[libwiicrypto] byteswap.h: Don't define inline if compiling as C++ with MSVC.
bank_init.c failed to compile with MSVC 2017 once switched to C++:

c:\program files (x86)\microsoft visual studio\2017\professional\vc\tools\msvc\14.16.27023\include\xkeycheck.h(207): error C4005: 'inline': macro redefinition