Fix compile errors when building the debug build on Linux with -DENABLE_WERROR=ON.
Mostly just complaints about using strncpy(), which have been fixed
by switching to snprintf():

src/libwiicrypto/sig_tools.c: In function ‘sig_recrypt_ticket’:
src/libwiicrypto/sig_tools.c:298:9: error: ‘__builtin_strncpy’ specified bound 64 equals destination size [-Werror=stringop-truncation]
  298 |         strncpy(ticket->issuer, issuer, sizeof(ticket->issuer));
      |         ^

src/librvth/recrypt.cpp: In member function ‘int RvtH::recryptWiiPartitions(unsigned int, RVL_CryptoType_e, RvtH_Progress_Callback, void*, int)’:
src/librvth/recrypt.cpp:587:24: error: ‘char* __builtin_strncpy(char*, const char*, long unsigned int)’ specified bound 64 equals destination size [-Werror=stringop-truncation]
  587 |                 strncpy(tmdHeader->issuer, issuer_TMD, sizeof(tmdHeader->issuer));
      |                        ^
src/nusresign/resign-nus.cpp:358:16: error: ‘char* __builtin_strncpy(char*, const char*, long unsigned int)’ specified bound 64 equals destination size [-Werror=stringop-truncation]
  358 |         strncpy(pTicket->issuer, s_issuer_xs, sizeof(pTicket->issuer));
      |                ^
src/nusresign/resign-nus.cpp:359:16: error: ‘char* __builtin_strncpy(char*, const char*, long unsigned int)’ specified bound 64 equals destination size [-Werror=stringop-truncation]
  359 |         strncpy(pTmdHeader->rvl.issuer, s_issuer_cp, sizeof(pTmdHeader->rvl.issuer));
      |                ^
src/wadresign/resign-wad.cpp:639:16: error: ‘char* __builtin___strncpy_chk(char*, const char*, long unsigned int, long unsigned int)’ specified bound 64 equals destination size [-Werror=stringop-truncation]
  639 |         strncpy(tmdHeader->issuer, issuer_TMD, sizeof(tmdHeader->issuer));
      |                ^