[libwiicrypto] common.h: Added spaces to the ALIGN() macros.
It seems that without the spaces, use of ALIGN() with offsetof() causes
an error in MSVC 2010:

..\..\..\src\librvth\recrypt.cpp(563): error C2102: '&' requires l-value