appveyor.yml: Switch from MSVC 2013 to MSVC 2015.
The AppVeyor MSVC 2013 failed with this error:

src\qrvthtool\RvtHModel.cpp(162): error C2057: expected constant expression

This doesn't happen locally or with newer MSVC.
[static_assert() with an array::size(), which is constexpr.]