appveyor.cmd: Switch to MSVC 2015 and Qt 5.13.
MSVC 2013 doesn't like the updated Google Test:

extlib\googletest\googletest\include\gtest/internal/gtest-port.h(2102):
	error C3409: empty attribute block is not allowed

Also, Qt 5.8 isn't present on AppVeyor anymore. Use Qt 5.13, which is
available for MSVC 2015.