Fix compile errors when building the debug build on Linux with -DENABLE_WERROR=ON.
Mostly just need to check the result of fread(), e.g.:

src/libwiicrypto/bin2h.c: In function ‘main’:
src/libwiicrypto/bin2h.c:66:9: error: ignoring return value of ‘fread’ declared with attribute ‘warn_unused_result’ [-Werror=unused-result]
   66 |         fread(bin, 1, fsize, f);
      |         ^~~~~~~~~~~~~~~~~~~~~~~